version: '3.8'

services:
  streamlit:
    build: ./app
    ports:
      - "8501:8501"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      - health_network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql  # 数据持久化存储
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # 初始化脚本
    ports:
      - "3306:3306"
    networks:
      - health_network
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

networks:
  health_network:
    driver: bridge