version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=easyhealth
      - DB_PASSWORD=easyhealth123
      - DB_NAME=easyhealth

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=easyhealth
      - MYSQL_USER=easyhealth
      - MYSQL_PASSWORD=easyhealth123
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data: